### ISSUE TITLE
Unable to install gulp command failed

### ISSUE THREAD

**Issue by coolweb** [dodoalive/DoDomotic#1]
When I run gulp I have this error:
cb(err);
        ^

ReferenceError: cb is not defined
    at C:\Users\Christophe\Documents\GitHub\DoDomotic\server\gulpfile.js:53:9
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by dodoalive** [comment]
Hi, 

You must install mongodb and add the bin directory to the PATH environment variable (for example, C: \ Program Files \ MongoDB \ Server \ 3.4 \ bin)

I will create the readme.me to explain how to start the project from scratch.

Regards,

**Comment by coolweb** [comment]
After installing mongodb and it to the path, the following error occured:
[16:22:34] Using gulpfile ~\Documents\GitHub\DoDomotic\server\gulpfile.js
[16:22:34] Starting 'default'...
[16:22:34] Starting 'clean'...
[16:22:34] Finished 'default' after 118 ms
[16:22:34] Finished 'clean' after 140 ms
[16:22:34] Starting 'build:server'...
[16:22:34] Starting 'typescript:server'...
[16:22:35] Starting 'run:mongo'...
[16:22:35] Finished 'run:mongo' after 8.12 ms
[16:22:35] Finished 'build:server' after 1.13 s
src\server.ts(1,27): error TS2307: Cannot find module 'mongoose'.
src\server.ts(2,26): error TS2307: Cannot find module 'cron'.
src\server.ts(3,26): error TS2307: Cannot find module 'express'.
src\server.ts(4,23): error TS2307: Cannot find module 'path'.
src\server.ts(5,32): error TS2307: Cannot find module 'cookie-parser'.
src\server.ts(6,29): error TS2307: Cannot find module 'body-parser'.
src\server.ts(7,27): error TS2307: Cannot find module 'passport'.
src\server.ts(8,23): error TS2307: Cannot find module 'cors'.
src\server.ts(56,22): error TS2304: Cannot find name 'require'.
src\server.ts(68,47): error TS2304: Cannot find name '__dirname'.

**Comment by coolweb** [comment]
I found but strange, there are 2 package.json file, so I need to run npm install into 2 folders....
